package io.pravah.common.domain;

import java.util.Objects;
import java.util.UUID;

/**
 * Value object representing a job identifier within a pipeline run.
 *
 * <p>Job IDs are UUIDs generated by the Execution Service for each job in a run.
 *
 * @see <a href="../../../../../../docs/lld/01-design-patterns.md">Design Patterns - Value
 *     Objects</a>
 */
public record JobId(UUID value) {

  /** Compact constructor with validation. */
  public JobId {
    Objects.requireNonNull(value, "Job ID cannot be null");
  }

  /**
   * Factory method for creating a JobId from a UUID.
   *
   * @param value the UUID value
   * @return a validated JobId
   */
  public static JobId of(UUID value) {
    return new JobId(value);
  }

  /**
   * Factory method for creating a JobId from a string.
   *
   * @param value the UUID string
   * @return a validated JobId
   * @throws IllegalArgumentException if the string is not a valid UUID
   */
  public static JobId of(String value) {
    Objects.requireNonNull(value, "Job ID string cannot be null");
    return new JobId(UUID.fromString(value));
  }

  /**
   * Generate a new random JobId.
   *
   * @return a new JobId with a random UUID
   */
  public static JobId generate() {
    return new JobId(UUID.randomUUID());
  }

  @Override
  public String toString() {
    return value.toString();
  }
}
