package io.pravah.common.domain;

import java.util.Objects;
import java.util.UUID;

/**
 * Value object representing a pipeline identifier.
 * <p>
 * Pipeline IDs are UUIDs generated by the Pipeline Service during pipeline creation.
 *
 * @see <a href="../../../../../../docs/lld/01-design-patterns.md">Design Patterns - Value Objects</a>
 */
public record PipelineId(UUID value) {

    /**
     * Compact constructor with validation.
     */
    public PipelineId {
        Objects.requireNonNull(value, "Pipeline ID cannot be null");
    }

    /**
     * Factory method for creating a PipelineId from a UUID.
     *
     * @param value the UUID value
     * @return a validated PipelineId
     */
    public static PipelineId of(UUID value) {
        return new PipelineId(value);
    }

    /**
     * Factory method for creating a PipelineId from a string.
     *
     * @param value the UUID string
     * @return a validated PipelineId
     * @throws IllegalArgumentException if the string is not a valid UUID
     */
    public static PipelineId of(String value) {
        Objects.requireNonNull(value, "Pipeline ID string cannot be null");
        return new PipelineId(UUID.fromString(value));
    }

    /**
     * Generate a new random PipelineId.
     *
     * @return a new PipelineId with a random UUID
     */
    public static PipelineId generate() {
        return new PipelineId(UUID.randomUUID());
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
