package io.pravah.common.domain;

import java.util.Objects;
import java.util.UUID;

/**
 * Value object representing a pipeline run identifier.
 *
 * <p>Run IDs are UUIDs generated by the Execution Service when a pipeline is triggered.
 *
 * @see <a href="../../../../../../docs/lld/01-design-patterns.md">Design Patterns - Value
 *     Objects</a>
 */
public record RunId(UUID value) {

  /** Compact constructor with validation. */
  public RunId {
    Objects.requireNonNull(value, "Run ID cannot be null");
  }

  /**
   * Factory method for creating a RunId from a UUID.
   *
   * @param value the UUID value
   * @return a validated RunId
   */
  public static RunId of(UUID value) {
    return new RunId(value);
  }

  /**
   * Factory method for creating a RunId from a string.
   *
   * @param value the UUID string
   * @return a validated RunId
   * @throws IllegalArgumentException if the string is not a valid UUID
   */
  public static RunId of(String value) {
    Objects.requireNonNull(value, "Run ID string cannot be null");
    return new RunId(UUID.fromString(value));
  }

  /**
   * Generate a new random RunId.
   *
   * @return a new RunId with a random UUID
   */
  public static RunId generate() {
    return new RunId(UUID.randomUUID());
  }

  @Override
  public String toString() {
    return value.toString();
  }
}
