server:
  port: 8080

spring:
  application:
    name: service-a

service-b:
  url: ${SERVICE_B_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    io.pravah.playground.otel: DEBUG
    io.opentelemetry: INFO
