package io.pravah.common.domain;

import java.util.Objects;
import java.util.UUID;

/**
 * Value object representing a user identifier.
 *
 * <p>User IDs are UUIDs generated by the Tenant Service during user creation.
 *
 * @see <a href="../../../../../../docs/lld/01-design-patterns.md">Design Patterns - Value
 *     Objects</a>
 */
public record UserId(UUID value) {

  /** Compact constructor with validation. */
  public UserId {
    Objects.requireNonNull(value, "User ID cannot be null");
  }

  /**
   * Factory method for creating a UserId from a UUID.
   *
   * @param value the UUID value
   * @return a validated UserId
   */
  public static UserId of(UUID value) {
    return new UserId(value);
  }

  /**
   * Factory method for creating a UserId from a string.
   *
   * @param value the UUID string
   * @return a validated UserId
   * @throws IllegalArgumentException if the string is not a valid UUID
   */
  public static UserId of(String value) {
    Objects.requireNonNull(value, "User ID string cannot be null");
    return new UserId(UUID.fromString(value));
  }

  /**
   * Generate a new random UserId.
   *
   * @return a new UserId with a random UUID
   */
  public static UserId generate() {
    return new UserId(UUID.randomUUID());
  }

  @Override
  public String toString() {
    return value.toString();
  }
}
